#!/usr/bin/env python3
"""
gen_queries.py — generate Microsoft Defender Advanced Hunting KQL, one query per
machine group, from a tenant config file.

Standard library only. No network. No secrets. Reads your config.json, writes one
`.kql` per `machine_groups` entry plus a copy-paste checklist. You then run each
query in YOUR own authenticated Defender browser session and export the results
to CSV — Claude never touches the portal or your data.

Usage:
    python3 gen_queries.py --config config.json --out out/queries
    python3 gen_queries.py --config ../assets/config.example.json   # dry preview
"""
import argparse
import json
import os
import sys


def load_iocs(cfg, base_dir):
    """Merge inline IOCs with an optional external ioc_file."""
    iocs = {"domains": [], "urls": [], "hashes": []}
    inline = cfg.get("iocs") or {}
    for k in iocs:
        iocs[k].extend(inline.get(k) or [])

    ioc_file = cfg.get("ioc_file")
    if ioc_file:
        path = ioc_file if os.path.isabs(ioc_file) else os.path.join(base_dir, ioc_file)
        with open(path, "r", encoding="utf-8") as fh:
            raw = fh.read().strip()
        try:
            data = json.loads(raw)
            for k in iocs:
                iocs[k].extend(data.get(k) or [])
        except json.JSONDecodeError:
            # newline-delimited: classify each line by shape
            for line in raw.splitlines():
                tok = line.strip()
                if not tok or tok.startswith("#"):
                    continue
                iocs[classify(tok)].append(tok)

    # de-dup, preserve order
    for k in iocs:
        iocs[k] = list(dict.fromkeys(iocs[k]))
    return iocs


def classify(token):
    """Best-effort: hash vs url vs domain."""
    t = token.strip()
    hexlen = len(t)
    if all(c in "0123456789abcdefABCDEF" for c in t) and hexlen in (32, 40, 64):
        return "hashes"
    if "://" in t or "/" in t:
        return "urls"
    return "domains"


def kql_list(values):
    """Render a list of strings as a KQL dynamic([...]) literal, safely escaped."""
    escaped = [v.replace("\\", "\\\\").replace('"', '\\"') for v in values]
    inner = ", ".join('"{0}"'.format(v) for v in escaped)
    return "dynamic([{0}])".format(inner)


HEADER = """// ===========================================================================
// Defender Advanced Hunting — machine group: {group}
// Generated by soc-investigator/gen_queries.py — DO NOT hand-edit; edit config.json
// Look-back: {days}d  |  IOCs: {ndomains} domain(s), {nurls} url(s), {nhashes} hash(es)
// Run in https://security.microsoft.com -> Hunting -> Advanced hunting, then Export to CSV.
// ===========================================================================
"""

BODY = """let LookBack = {days}d;
let SuspectDomains = {domains};
let SuspectUrls = {urls};
let SuspectHashes = {hashes};
// --- Network contact with suspect domains / urls / IPs ---
let NetworkHits =
    DeviceNetworkEvents
    | where Timestamp > ago(LookBack)
    | where RemoteUrl has_any (SuspectDomains)
         or RemoteUrl has_any (SuspectUrls)
         or RemoteIP in (SuspectDomains)
    | extend Ioc = coalesce(RemoteUrl, RemoteIP), IocType = "network"
    | project Timestamp, DeviceId, DeviceName, OSPlatform, DeviceType,
              AccountName = InitiatingProcessAccountName, Ioc, IocType,
              RemoteIP, SHA256 = InitiatingProcessSHA256,
              ProcessName = InitiatingProcessFileName;
// --- File executions matching suspect hashes ---
let FileHits =
    DeviceFileEvents
    | where Timestamp > ago(LookBack)
    | where SHA256 in~ (SuspectHashes) or SHA1 in~ (SuspectHashes) or MD5 in~ (SuspectHashes)
    | extend Ioc = coalesce(SHA256, SHA1, MD5), IocType = "file"
    | project Timestamp, DeviceId, DeviceName, OSPlatform, DeviceType,
              AccountName = InitiatingProcessAccountName, Ioc, IocType,
              RemoteIP = "", SHA256,
              ProcessName = FileName;
union NetworkHits, FileHits
| where {filter}
| extend MachineGroup = "{group}"
| project Timestamp, DeviceName, DeviceId, MachineGroup, OSPlatform, DeviceType,
          AccountName, Ioc, IocType, RemoteIP, SHA256, ProcessName
| sort by Timestamp desc
"""


def build_query(group, iocs, days):
    head = HEADER.format(
        group=group["name"], days=days,
        ndomains=len(iocs["domains"]), nurls=len(iocs["urls"]), nhashes=len(iocs["hashes"]),
    )
    body = BODY.format(
        days=days,
        domains=kql_list(iocs["domains"]),
        urls=kql_list(iocs["urls"]),
        hashes=kql_list(iocs["hashes"]),
        filter=group["filter"],
        group=group["name"],
    )
    return head + body


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate per-machine-group Defender KQL from config.")
    ap.add_argument("--config", required=True, help="Path to config.json")
    ap.add_argument("--out", default="out/queries", help="Output directory for .kql files")
    args = ap.parse_args(argv)

    with open(args.config, "r", encoding="utf-8") as fh:
        cfg = json.load(fh)
    base_dir = os.path.dirname(os.path.abspath(args.config))

    days = int(cfg.get("time_window_days", 7))
    groups = cfg.get("machine_groups") or []
    if not groups:
        print("ERROR: config has no machine_groups.", file=sys.stderr)
        return 2

    iocs = load_iocs(cfg, base_dir)
    total_iocs = sum(len(v) for v in iocs.values())
    if total_iocs == 0:
        print("ERROR: no IOCs found in config (iocs/ioc_file are empty).", file=sys.stderr)
        return 2

    os.makedirs(args.out, exist_ok=True)
    written = []
    for g in groups:
        fname = os.path.join(args.out, "defender_{0}.kql".format(g["name"]))
        with open(fname, "w", encoding="utf-8") as fh:
            fh.write(build_query(g, iocs, days))
        written.append(fname)

    defender_url = (cfg.get("portals") or {}).get("defender_url", "https://security.microsoft.com")

    print("Generated {0} Defender query file(s) for {1} IOC(s) "
          "({2} domains, {3} urls, {4} hashes):".format(
              len(written), total_iocs,
              len(iocs["domains"]), len(iocs["urls"]), len(iocs["hashes"])))
    for f in written:
        print("  - {0}".format(f))
    print()
    print("COWORK CHECKLIST — do this in YOUR browser (Claude never connects):")
    print("  1. Open {0}".format(defender_url))
    print("  2. For EACH .kql file above:")
    print("       a. Paste its contents into Advanced hunting and Run.")
    print("       b. Click Export -> CSV.")
    print("       c. Save the CSV into ./exports/defender/ (keep the group name).")
    print("  3. Then run:  python3 scripts/enrich.py --config {0}".format(args.config))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
