#!/usr/bin/env node
/**
 * build-index.mjs — generate a themeable, switchable tutorials index.html from a catalog.
 * Light/dark toggle (persisted in localStorage), configurable logo + accent from
 * tutorial.config.json, and a live filter box. Pure HTML/CSS/JS — no build step.
 *
 * Usage:
 *   node build-index.mjs --catalog public/tutorials/catalog.json \
 *                        --config tutorial.config.json \
 *                        --out public/tutorials/index.html
 *
 * Copies templates/theme.css next to the generated index so the page is self-contained.
 */
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
function arg(name, fb) { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? process.argv[i + 1] : fb; }
function esc(s = '') { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

const catalogPath = resolve(arg('catalog', 'catalog.json'));
if (!existsSync(catalogPath)) { console.error(`ERROR: catalog not found: ${catalogPath}`); process.exit(2); }
const catalog = JSON.parse(readFileSync(catalogPath, 'utf8'));

const cfgPath = arg('config');
const cfg = cfgPath && existsSync(resolve(cfgPath)) ? JSON.parse(readFileSync(resolve(cfgPath), 'utf8')) : {};
const brand = cfg.brand || {};
const project = cfg.project || {};

const out = resolve(arg('out', join(dirname(catalogPath), 'index.html')));
const outDir = dirname(out);
mkdirSync(outDir, { recursive: true });

// ship theme.css alongside the index so it renders anywhere
const themeSrc = resolve(__dirname, '..', 'templates', 'theme.css');
if (existsSync(themeSrc)) copyFileSync(themeSrc, join(outDir, 'theme.css'));

const accent = brand.accent || '#2563eb';
const accentDark = brand.accentDark || accent;
const theme = brand.defaultTheme === 'light' ? 'light' : 'dark';
const logo = brand.logo || '';
const title = `${project.name || 'App'} — Tutorials`;
const items = catalog.items || catalog.tutorials || [];

const card = (t) => `      <article class="card" data-status="${esc(t.status || '')}">
        <a class="thumb" href="${esc(t.package || t.video || '#')}">${
          t.poster ? `<img loading="lazy" src="${esc(t.poster)}" alt="${esc(t.title)}"/>` : `<div class="thumb-ph">▶</div>`
        }</a>
        <div class="body">
          <h3>${esc(t.title)}${t.status ? ` <span class="pill ${esc(t.status)}">${esc(t.status)}</span>` : ''}</h3>
          <p class="muted">${esc(t.description || '')}</p>
          <div class="actions">${
            (t.video ? `<a href="${esc(t.video)}">▶ Watch</a>` : '') +
            (t.package ? `<a href="${esc(t.package)}">Open page</a>` : '')
          }</div>${t.recordedAt ? `\n          <div class="meta">recorded ${esc(t.recordedAt)}</div>` : ''}
        </div>
      </article>`;

const html = `<!DOCTYPE html>
<html lang="en" data-theme="${theme}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(title)}</title>
  <link rel="stylesheet" href="./theme.css" />
  <style>:root{--accent:${esc(accent)}}:root[data-theme="dark"]{--accent:${esc(accentDark)}}</style>
</head>
<body>
  <header class="site">
    <div class="brand">${logo ? `<img class="logo" src="${esc(logo)}" alt="" />` : ''}<h1>${esc(title)}</h1></div>
    <div class="controls">
      <input id="q" type="search" placeholder="Filter tutorials…" aria-label="Filter tutorials" />
      <button id="theme-toggle" title="Toggle light / dark" aria-label="Toggle light / dark">◐</button>
    </div>
  </header>
  <main>
    <p class="lead">${esc(catalog.tagline || 'Narrated, step-by-step walkthroughs.')}</p>
    <section id="grid" class="grid">
${items.map(card).join('\n')}
    </section>
    <p class="empty" hidden>No tutorials match your filter.</p>
  </main>
  <footer>Generated by the <a href="https://github.com/Kaidanov/grekai-skills-4all/tree/main/skills/tutorial">tutorial</a> skill · ${items.length} tutorial(s).</footer>
  <script>
    const root = document.documentElement, KEY = 'tutorial-theme';
    const saved = localStorage.getItem(KEY); if (saved) root.setAttribute('data-theme', saved);
    document.getElementById('theme-toggle').onclick = () => {
      const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', next); localStorage.setItem(KEY, next);
    };
    const q = document.getElementById('q');
    const cards = [...document.querySelectorAll('.card')];
    const empty = document.querySelector('.empty');
    q.addEventListener('input', () => {
      const v = q.value.toLowerCase(); let shown = 0;
      cards.forEach((c) => { const hit = c.textContent.toLowerCase().includes(v); c.hidden = !hit; if (hit) shown++; });
      empty.hidden = shown > 0;
    });
  </script>
</body>
</html>
`;
writeFileSync(out, html);
console.log(`OK  ${out}  (${items.length} tutorial(s))`);
